services:
  app:
    build: .
    volumes:
      - ./source:/app
    ports:
      - "8080:8080" # Adjust port according to your server configuration
    # Enable debugging capabilities
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
